### PR TITLE
Added footer with social links

### PR DESCRIPTION
**Pull request by mfazza**
New dependency is 'styled icons' since 'styled components' is already in use.

### CODE REVIEW

**Comment by mckernanin** [comment]
@mattfazza thanks! I'll check it out!

**Comment by mckernanin** [comment]
@mattfazza would you mind adding a link to our youtube channel? https://www.youtube.com/channel/UC0l91ig1FOXYaZonnr9m1lw

**Comment by mfazza** [comment]
No, not at all!

**Comment by mfazza** [comment]
I like the way it looks with only the social links at the bottom.  Looks clean to me even with the fourth icon added 🤠

**Comment by mckernanin** [comment]
Good stuff, thanks @mattfazza.

Closes #19

**Pull request merged**
